version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    restart: always
    ports:
      - '3500:3500'
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    command: npm run start:dev
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports: 
      - '5432:5432'
    volumes:
      - my-discord-db:/var/lib/postgresql/data

volumes:
  my-discord-db:
    driver: local