name: Deploy Staging

on:
  push:
    branches:
      - staging
env:
  VITE_API_URL: ${{ secrets.VITE_API_URL }}
  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: 'Staging'
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config fly.staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  run-e2es:
    timeout-minutes: 60
    needs:
      - deploy
    if: needs.deploy.result == 'success'
    runs-on: ubuntu-latest
    environment: 'Staging'
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'syoupheng/my-discord-react-ui'
          ref: 'staging'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          npx playwright test --project=chromium
          npx playwright test --project=firefox
          npx playwright test --project=webkit
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e/playwright-report
          path: e2e/playwright-report/
          retention-days: 30
